In [ ]:
#import pandas for our train_data
import pandas as pd

In [2]:
#read in our dataframe
kdata = pd.read_csv("banknotes.csv")

In [3]:
#first 5 rows
kdata.head()

variance  curtosis  class
0  -0.89569 -3.606700      1
1   3.47690  2.530000      0
2   3.91020 -2.453400      0
3   0.60731 -4.772000      1
4   2.37180  0.015989      0

In [ ]:
#features from our tain_data
feats = kdata[['variance', 'curtosis']].values
print(feats)

array([[-0.89569 , -3.6067  ],
       [ 3.4769  ,  2.53    ],
       [ 3.9102  , -2.4534  ],
       ...,
       [-0.025314, -0.11339 ],
       [-2.234   ,  7.4936  ],
       [ 4.7285  , -0.28305 ]], shape=(1372, 2))

In [19]:
#targets from our train data
target = kdata['class'].values
print(target)

[1 0 0 ... 1 1 0]


In [ ]:
#importing numpy for our arrays
import numpy as np

In [9]:
#new data item to be classified
new_data = np.array([2.37180, 0.015989])
new_data

array([2.3718  , 0.015989])

In [11]:
#define function for euclidian distance
def euc_dist(new_d, feat_d):
    m = feat_d.shape[0] #number of rows in feature data/ determine the dimensions of array
    distance = np.zeros(m) #initialize array of zeros
    for i in range(m):
        distance[i] = np.sqrt((new_d[0] - feat_d[i][0])**2 + (new_d[1] - feat_d[i][1])**2)
    return distance

In [12]:
# find the distances of each item in our data
d = euc_dist(new_data, feats)
d

array([4.87856193, 2.74617868, 2.9093911 , ..., 2.40060294, 8.78225825,
       2.3755966 ], shape=(1372,))

In [14]:
#function to predict the target given k neighbors
def pred_knn(euc_d, targ, k):
    m = targ.shape[0] #number of rows in target data/dimensions of the array
    arr = np.zeros([m,2]) #initialize array of zeros with dimensions of m x 2 (2 columns)
    for i in range(m):
        arr[i] = np.array([euc_d[i], targ[i]])
        print(arr[i])
        sort_arr = np.sort(arr, axis=0)
        sort_arr = sort_arr[:k]
    return sort_arr

In [ ]:
first_k = pred_knn(d, target, 5) #predict the target given 5 neighbors

[4.87856193 1.        ]
[2.74617868 0.        ]
[2.9093911 0.       ]
[5.10277019 1.        ]
[0. 0.]
[4.58752643 0.        ]
[2.17627563 0.        ]
[1.55969808 0.        ]
[1.76450296 0.        ]
[2.48197276 1.        ]
[5.57839079 1.        ]
[3.76208424 1.        ]
[8.60670281 0.        ]
[2.17891478 0.        ]
[4.20815102 1.        ]
[3.88884882 0.        ]
[4.38408387 0.        ]
[1.98226083 1.        ]
[3.35755045 0.        ]
[8.32842453 0.        ]
[2.80872893 0.        ]
[5.16103253 0.        ]
[1.87738714 0.        ]
[2.39035691 0.        ]
[6.02549524 1.        ]
[6.33631206 1.        ]
[2.33300856 0.        ]
[9.40939491 1.        ]
[3.99188426 1.        ]
[3.52097858 1.        ]
[6.97924668 1.        ]
[2.82542848 0.        ]
[1.31469975 0.        ]
[5.02339576 1.        ]
[5.14638982 1.        ]
[5.29807882 1.        ]
[0.91912055 0.        ]
[0.8533717 0.       ]
[8.13943165 0.        ]
[3.90835996 0.        ]
[4.90879017 1.        ]
[0.4966562 0.       ]
[4.99107819 0.

In [17]:
first_k

array([[0.        , 0.        ],
       [0.14442527, 0.        ],
       [0.20120186, 0.        ],
       [0.25440134, 0.        ],
       [0.27888426, 0.        ]])